### ISSUE TITLE
how can I set training steps and epochs?

### ISSUE THREAD

**Issue by ZoeJiang2222** [ideafang/RouteNet-Pytorch#1]
I’ve just download the zip, and try to run the code, but I didn’t find the epoch and step, did I miss something? I’d like to try to modify them in trainer.
By the way, I am going to reimplement Routenet with PyTorch, PyTorch-lightning is so easy but difficult for me to add other modules, have you ever tried rewrite only in PyTorch or PyTorch-geometric?
Thanks a lot for your work, and sincerely hope you can help me a bit.

**Comment by ideafang** [comment]
Sorry for the late reply. Can you give more detailed error reporting steps. For example, which step did you perform when this problem occurred?

Also, after trying it, I don't think it's a good idea to reproduce RouteNet with pytorch. At least until Pytorch's variable-length matrices are perfected, Tensorflow's RaggedTensor may be more suitable for modeling message passing sequences of different lengths in RouteNet.

**Comment by ZoeJiang2222** [comment]
Thanks for your apply, I've defined max-epochs in trainer, but there's something wrong in trainig process:

> Epoch 0:  69%|████████████████Traceback (most recent call last):█████████████████████▍                               | 539500/778500 [1:25:32<37:53, 105.11it/s, loss=3.35e-05, v_num=3]
  File "main.py", line 16, in <module>
    trainer.fit(model, dm)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1205, in _run_train
    self.fit_loop.run()
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.on_advance_end()
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 250, in on_advance_end
    self._run_validation()
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 308, in _run_validation
    self.val_loop.run()
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 121, in advance
    batch = next(data_fetcher)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/demo1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/code/dataloader.py", line 17, in __getitem__
    y = torch.FloatTensor(s[self.label_str])
KeyError: 'delay'
Epoch 0:  69%|██████▉   | 539500/778500 [1:25:45<37:59, 104.84it/s, loss=3.35e-05, v_num=3]

**Comment by ideafang** [comment]
Dear Zoe, thanks for your question, this is indeed a bug. Fortunately, the latest commit of `dataloader.py` has solved this problem. You can directly replace `dataloader.py` with the latest version for testing.

**Comment by ZoeJiang2222** [comment]
Dear Fang,
thanks for your answer, I've tried the newest version, but the bug still exists after finishing Epoch 0, is there anything wrong?
Sincerely hope you can help me.

![1](https://github.com/ideafang/RouteNet-Pytorch/assets/102734121/d78c7e9a-ba5f-49b5-892c-16af4d951963)
![2](https://github.com/ideafang/RouteNet-Pytorch/assets/102734121/ced58bdd-d55d-42c9-91e6-6a2b83289ced)

**Comment by ideafang** [comment]
Dear Zoe, 
Thanks for your testing. I've updated the `dataloader.py` again to fix this issue. You can update your file again and it will work well. Hoping to hear your success! Please feel free to contact me if you meet other errors : )
Henry

**Comment by ZoeJiang2222** [comment]
Dear Henry,
Thanks a lot for your help, I've made it!
And I wonder have you ever tested how to set the best epoch, the training process is a little slow.
Sincerely thank you for all you've done : )
Zoe

**Comment by ZoeJiang2222** [comment]
Dear Henry,
Thanks a lot for your help, I've made it!
And I wonder have you ever tested how to set the best epoch, the training process is a little slow.
Sincerely thank you for all you've done : )
Zoe

**Comment by ideafang** [comment]
Hi Zoe, 

I recommend you to see my another repo: [MixerNet](https://github.com/ideafang/MixerNet). It is one of our paper to improve RouteNet. We use the same dataset and build our model by Pytorch. It is also optimized specifically for training acceleration. If you find this code useful in your research please cite it.

Henry

**Comment by ZoeJiang2222** [comment]
Hi Henry,

Thanks for your advice, I will read the  paper you mentioned.
You really did a great job, thanks a lot.

Zoe
